Task_1_4_1
MelloTheCatLover/OOP pull request #10
Opened 2023-11-20 02:59 UTC by MelloTheCatLover

2023-11-22 06:16 UTC, galinabykova requested changes

2023-11-22 06:16 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/Pair.java
> +public class Pair<K, V> implements Serializable {
есть подозрение, что ты хотел использовать tuple

2023-11-22 06:16 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/StudentRecordBook.java
> +public class StudentRecordBook {
должна быть какая-то информация о студенте, хотя бы имя

2023-11-22 06:16 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/StudentRecordBook.java
> +    public RedCertificateStatus checkRedCertificateStatus() {
крутая идея возвращать ещё и причину

2023-11-22 06:16 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/StudentRecordBook.java
> +        private List<RedDiplomaReason> reasons;
не уверена, что это хорошее решение, делать enum с полем, которое используется только при         notEligible. Впрочем, эта штука используется только для возврата из одной функции, кажется, так что можешь не менять, просто подумай, как это можно было бы реализовать иначе, какие есть плюсы и минусы у этого и других подходов, обсудим при очной защите

2023-11-22 07:33 UTC, MelloTheCatLover commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/StudentRecordBook.java
> +public class StudentRecordBook {
Просто я думал, что студент - более общий класс и к нему относится его зачетная книжка. Добавлю имя в этот класс

2023-11-22 07:39 UTC, MelloTheCatLover commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/Pair.java
> +public class Pair<K, V> implements Serializable {
Да, я так и не нашел ничего, видимо плохо искал, есть реализация tuple в стандартных библиотеках. Можешь ссылку кинуть?

2023-11-22 08:19 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/Pair.java
> +public class Pair<K, V> implements Serializable {
Прости, я перепутала с другим языком, в джава для такого действительно ничего нет( 
Вот тут
https://habr.com/ru/articles/123790/
небольшой холивар на тему пар в плюсах. Я считаю, что пары часто нужны для того, чтобы по-быстрому что-то написать, но с ооп они как-то не слишком дружат. 

Судя по твоему коду, кажется, что тебе можно список просто заменить на HashMap, и пары тебе не нужны. Переделай, пожалуйста, таким образом.

Кстати, чтобы подключить стороннюю библиотеку, её надо прописать в gradle

2023-11-22 08:22 UTC, galinabykova requested changes

2023-11-22 08:22 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/StudentRecordBook.java
> +            finalGradesBySemester.get(semester).forEach((subject, averageGrade)
попробуй тут обойтись без for и без forEach

2023-11-22 08:22 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/kozoliy/StudentRecordBook.java
> +            finalGradesBySemester.get(semester).forEach((subject, averageGrade)
наверно, тебе понадобится collect

2023-11-23 14:56 UTC, galinabykova requested changes
удали, пожалуйста, файлик с парами

2023-11-23 18:25 UTC, galinabykova approved these changes

2023-11-24 04:03 UTC, merged