Task_1_5_1
MelloTheCatLover/OOP pull request #11
Opened 2023-12-06 16:59 UTC by MelloTheCatLover

2023-12-06 20:25 UTC, galinabykova requested changes

2023-12-06 20:25 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/kozoliy/Calculator.java
> +    public static class Factory {
почему ты решил сделать фабрику вложенным классом?

2023-12-06 20:25 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/kozoliy/Calculator.java
> +    public static class Sin implements Operator {
нужно вынести операции в отдельные файлы, потому что сейчас этот файл неоправданно большой, с ним будет неудобно работать, и будет неудобно редактировать код совместно

2023-12-07 04:34 UTC, MelloTheCatLover commented on Task_1_5_1/src/main/java/ru/nsu/kozoliy/Calculator.java
> +    public static class Factory {
Когда изучал фабрику все в одном файле тестировал

2023-12-07 04:34 UTC, MelloTheCatLover commented on Task_1_5_1/src/main/java/ru/nsu/kozoliy/Calculator.java
> +    public static class Factory {
Не подумал

2023-12-07 04:34 UTC, MelloTheCatLover commented on Task_1_5_1/src/main/java/ru/nsu/kozoliy/Calculator.java
> +    public static class Sin implements Operator {
Сделаю

2023-12-07 10:03 UTC, galinabykova requested changes

2023-12-07 10:03 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/kozoliy/Factory.java
> +        if (type.equals("+")) {
кажется, тут будет лучше использовать switch, будет читаемее

2023-12-07 10:03 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/kozoliy/Multiply.java
> +            throw new EmptyStackException();
а зачем ты его перехватываешь, если его же бросаешь?

2023-12-13 11:25 UTC, galinabykova approved these changes

2023-12-13 11:28 UTC, merged