Task_1_5_2
MelloTheCatLover/OOP pull request #12
Opened 2023-12-20 17:52 UTC by MelloTheCatLover

2023-12-21 15:19 UTC, galinabykova requested changes

2023-12-21 15:19 UTC, galinabykova commented on Task_1_5_2/src/main/java/ru/nsu/kozoliy/CommandLineParserNotebook.java
> +    ) {
мне не нравится этот метод. Здесь ты разбираешь аргументы командной строки и выполняешь некоторую "полезную" работу (сериализуешь, выводишь строчки). Функция большая, и в ней сложно разобраться, нужно думать, к чему относится каждая строчка, к разбору аргументов или к "полезной" работе. Лучше отделить "полезную" работу так, чтобы в этой функции ты максимум вызывал методы "Вывести по ключевым словам", "Добавить заметку" и т.д., а "полезная" работа была отделена

2023-12-21 15:19 UTC, galinabykova commented on Task_1_5_2/src/main/java/ru/nsu/kozoliy/CommandLineParserNotebook.java
> +            } else if (cmd.hasOption("rm")) {
как будет работать твоя программа, если ей на вход передать несколько ключевых слов, например

notebook -add "Title" "content" -rm

?

2023-12-27 08:52 UTC, MelloTheCatLover commented on Task_1_5_2/src/main/java/ru/nsu/kozoliy/CommandLineParserNotebook.java
> +            } else if (cmd.hasOption("rm")) {
Missing required parameter for option '--rm' (<remove>)
        Usage: notebook [-hV] [-r=<remove>] [-a=<add> <add>]... [-s[=<show>...]]...
        Command-line interface for interacting with a Notebook.
          -a, --add=<add> <add>    Add a note
          -h, --help               Show this help message and exit.
          -r, --rm=<remove>        Remove a note
          -s, --show[=<show>...]   Show notes
          -V, --version            Print version information and exit.
          
          
          Вот такое

2023-12-27 09:18 UTC, galinabykova requested changes
reviewdog

2023-12-27 10:04 UTC, galinabykova approved these changes

2024-01-09 11:50 UTC, merged