Task_2_1_1
MelloTheCatLover/OOP pull request #13
Opened 2024-02-19 09:56 UTC by MelloTheCatLover

2024-02-19 11:23 UTC, MelloTheCatLover commented
По неизвестной мне причине не проходит тест по покрытию методы по отрисовке статистики. Если раскомментировать, то можно будет посмотреть сравнение

2024-02-19 12:14 UTC, galinabykova requested changes
исправь замечания reviewdog и приложи картинку графика, например, скрин в виде png или какого-то другого формата

2024-02-19 12:14 UTC, galinabykova commented on Task_1_5_2/Task_1_5_2.iml
кажется, у тебя вся эта папка не должна быть в этом коммите

2024-02-19 12:14 UTC, galinabykova commented on Task_1_5_2/Task_1_5_2.iml
1_5_2

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/kozoliy/SequentialDetector.java
> +    static boolean isPrime(long number) {
клёвая оптимизация, не видела такого)

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/kozoliy/SequentialDetector.java
> +    static boolean isPrime(long number) {
но плохо, что такой не самый очевидный код у тебя три раза дублируется( избавься от дублирования, пожалуйста

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/kozoliy/ChartBuilder.java
> +public class ChartBuilder {
хорошо, что ты сделал отдельный класс для этого)

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/kozoliy/ChartBuilder.java
> +        javax.swing.SwingUtilities.invokeLater(() -> {
swing это устаревшая библиотека для UI. Странно, что ты решил её для чего-то использовать

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/kozoliy/ChartBuilder.java
> +        javax.swing.SwingUtilities.invokeLater(() -> {
Аааааааа, ты графики в java рисовал

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/kozoliy/ChartBuilder.java
> +        javax.swing.SwingUtilities.invokeLater(() -> {
Сильно

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/kozoliy/ChartBuilder.java
> +public class ChartBuilder {
но плохо, что у тебя функция состоит из дублирования одного и того же кода. Если бы был общий интерфейс для всех решений, можно было бы сделать общую функцию

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/kozoliy/ParallelDetector.java
> +            final int end = (i == numThreads - 1) ? numbers.length : (i + 1)
почему ты решил сделать такое распределение задач по потокам?

2024-02-19 12:14 UTC, galinabykova commented on Task_2_1_1/src/test/java/TestDetector.java
нужно сделать больше тестов, рассмотреть крайние случаи. Ещё, мне кажется, было бы здорово разбить его не несколько файлов, потому что сейчас все тесты свалены в кучу и очень неудобно разбираться, что к чему относится

2024-02-20 05:07 UTC, galinabykova approved these changes

2024-03-05 04:44 UTC, merged