Task_2_2_1
MelloTheCatLover/OOP pull request #14
Opened 2024-04-08 11:23 UTC by MelloTheCatLover

2024-04-10 08:16 UTC, galinabykova requested changes

2024-04-10 08:16 UTC, galinabykova commented on Task_2_1_1/Task_2_1_1.iml
убери все лишние файлики, пожалуйста)

2024-04-10 08:16 UTC, galinabykova commented on Task_2_1_1/build/classes/java/main/ru/nsu/kozoliy/ChartBuilder.class
и вот эти)

2024-04-10 08:16 UTC, galinabykova commented on Task_2_2_1/build/classes/java/main/ru/nsu/kozoliy/Dto/BackerDto.class
и вот эти

2024-04-10 08:16 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/storage/Storage.java
> +    public boolean isFull() {
этот метод нужно использовать с осторожностью, так как он может вернуть устаревшее значение. Нужно прописать это в документации и отразить в названии

2024-04-10 08:16 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
что происходит с заказами, которые находятся в хранилищах, и заказами в процессе при остановке пиццы?

2024-04-10 08:21 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
вот этот ответ ожидаю в ближайшее время)

2024-04-13 13:43 UTC, MelloTheCatLover commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
При этом, заказы, которые еще не доставлены клиентам,  они в очереди заказов orders. При вызове метода endWorking(), они остаются и прекращается из обработка. То есть, они не будут  доставлены  до следующего запуска системы. Вот так

2024-04-13 13:47 UTC, MelloTheCatLover commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
Прости, у меня 3 почты, не увидел, что пришли правки

2024-04-14 07:31 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
кажется, тут сообщение потерялось)

2024-04-14 08:08 UTC, galinabykova requested changes

2024-04-14 08:08 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
> +    private final Queue<Order> orders;
мне кажется, синхронизацию этой очереди можно сделать в отдельном классе)

2024-04-14 08:08 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/Main.java
> +                        System.out.println("==================DAY" + i + "==================");
нужно сделать логгирование через какой-нибудь логгер)

2024-04-14 12:44 UTC, MelloTheCatLover commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/Main.java
> +                        System.out.println("==================DAY" + i + "==================");
Здесь нужно только для недели логгирование сделать или в целом для работы с пиццерией

2024-04-14 13:10 UTC, MelloTheCatLover commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
При остановке работы пиццерии все (пекари, курьеры и пользователи) останавливают свою работу. При вызове метода endWorking() также останавливаются все службы, но кроме того, вызывается метод notifyAll(), чтобы оповестить все потоки, ожидающие работы пиццерии

2024-04-15 03:43 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/Main.java
> +                        System.out.println("==================DAY" + i + "==================");
везде)

2024-04-15 03:46 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
а что происходит с заказом, который пекарь взял, но в процессе готовки его остановили? он теряется?

2024-04-15 03:47 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
если я правильно поняла твой код, у тебя он теряется, нужно сделать так, чтобы он не терялся (либо возвращался в пул заказов, либо готовился до конца). Если я ошиблась, напиши сюда об этом)

2024-04-15 13:00 UTC, MelloTheCatLover commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
Почему, вроде это предусмотрено. Если поток пекаря был прерван внутри цикла while, он поймает InterruptedException. В этом случае пекарь прервет свою работу, но при этом уже взятый заказ останется в системе, да. В следующий раз пекарь он попытается взять заказ из очереди и продолжить работу с ним. Так нельзя?

2024-04-15 15:51 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/kozoliy/model/Pizzeria.java
если "уже взятый заказ останется в системе" означает, что он нигде не сохраняется, то нет, нельзя, совсем теряться заказ не должен

2024-04-16 06:40 UTC, galinabykova approved these changes

2024-04-25 11:42 UTC, merged