Task_2_3_1
MelloTheCatLover/OOP pull request #15
Opened 2024-04-29 05:34 UTC by MelloTheCatLover

2024-04-29 08:48 UTC, galinabykova requested changes
У меня получилось запустить твою змейку, удалив строчки
```
sourceCompatibility = '17'
targetCompatibility = '17'
```
из build.gradle. Мягкий дедлайн засчитываю
Сейчас у тебя всё смешано в одном классе, нужно разделить View и Model, должен появиться fxml. Текстовое поле score должно быть определено в fxml, значение должно автоматически обновляться с помощью биндинга. Пожалуйста, не затягивай с правками, после этих изменений я буду смотреть код.

2024-05-01 17:34 UTC, galinabykova requested changes

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/.idea/compiler.xml
пожалуйста, удали ненужные файлики!!!

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/Controller.java
> +public class Controller implements Initializable {
Мне непонятно, Controller чего это)

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/Controller.java
> +    private Button startButton;
постарайся по минимуму вытаскивать компоненты интерфейса в поля

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/Controller.java
> +    private TextField foodCount;
попробуй не вытаскивать вот этот компонент, а поле foodCount из модели забиндить, чтобы оно автоматически менялось

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/Controller.java
> +                settings.setDifficulty(0.4);
это бы тоже в идеале забиндить, но скорее всего сложно будет) возможно даже в стандартном javafx для этого нет компонентов (я не знаю)

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/Snake.java
> +    private Direction direction = Direction.RIGHT;
вот это поле в модели, кажется, должно быть (или нет?)

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/Snake.java
> +    private int score = 0;
вот это точно к модели относится

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/Snake.java
> +        head.setTranslateX(settings.getWorldSizeX() / 2);
у тебя тут есть код, относящийся к бизнес-логике

2024-05-01 17:34 UTC, galinabykova commented on Task_2_3_1/src/main/resources/ru/nsu/kozoliy/keep_logo.png
а что за картинка?

2024-05-10 06:59 UTC, galinabykova requested changes
Привет, грустно, что ты не уложился в дедлайн, но главное, что ты проделал большую работу, чтобы понять, как устроены mv* паттерны. Я оставила комментарии, их править не надо, с ними надо ознакомиться, подробнее предлагаю обсудить проблемы твоего решения при очной защите (пожалуйста, не затягивай, а то я потом забуду, что надо обсудить, и это потом на экзамене может обернуться против тебя, важно, чтобы ты понял эту тему). Для засчитывания лабы нужно сделать ревьюдог и тестовое покрытие 80 процентов для всех классов модели, кроме Snake.

2024-05-10 06:59 UTC, galinabykova commented on Task_2_3_1/.idea/compiler.xml
удали, пожалуйста, эти файлики. Если у тебя есть проблемы с .gitignore, давай обсудим их при очной защите, мне не очень нравится постоянно писать однотипные комментарии)

2024-05-10 06:59 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/models/Food.java
> +    int x;
согласно вашему стилю кода, названия переменных должны состоять хотя бы из двух букв, причём первые две буквы маленькие

2024-05-10 06:59 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/models/Model.java
> +    SnakeGameViewModel snakeGameViewModel = new SnakeGameViewModel(this);
меня очень удивила эта строчка. Если бы у тебя не было ссылки на  ViewModel, кажется, что в целом ты бы даже мог сделать два пользовательских интерфейса (например, один консольный, другой с помощью javafx). Также классы бизнес-логики могут как-то сохраняться в бд, сериализоваться и т.д., и поэтому, мне кажется, что эта ссылка создаёт сильное ограничение, и лучше не хранить ViewModel в Model

ViewModel обновляет, и ViewModel же читает данные из модели (опустим сейчас биндинг).

2024-05-10 06:59 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/viewModel/SnakeGameViewModel.java
> +    public void generateNewFood(){
новая еда должна генерироваться в Моделе, а тут только отрисовываться

2024-05-10 12:32 UTC, MelloTheCatLover commented on Task_2_3_1/.idea/compiler.xml
Да, про ненужные файлики согласен, мне они тоже не нравятся, но каждый раз когда я берусь за gitignore  я все ломаю. Прости

2024-05-11 15:40 UTC, galinabykova approved these changes

2024-05-24 05:18 UTC, galinabykova requested changes
reviewdog

2024-05-24 05:18 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/models/BadSnake.java
если я правильно поняла, то у тебя всего одна змейка, нужно чтобы была возможность задавать змейки с разными стратегиями (хотя бы две)
![image](https://github.com/MelloTheCatLover/OOP/assets/86754545/6723db9b-635a-4341-82fb-c254bb9011b7)

2024-05-24 05:18 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/models/Model.java
> +    public void detectCollision(SnakePart tail) {
а почему этот метод исключён из общей статистики по тестам?

2024-05-24 05:18 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/models/Model.java
> +    public void detectCollision(SnakePart tail) {
а что происходит при пересечении змеек друг другом?

2024-06-04 10:52 UTC, galinabykova approved these changes

2024-06-04 10:52 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/kozoliy/models/SmartSnake.java
> +        switch (direction) {
кажется, это кусок кода дублируется. Возможно стоило сделать SmartSnake и BadSnake частью общей иерархии

2024-06-05 09:28 UTC, merged