Task_1_1_2
MelloTheCatLover/OOP pull request #3
Opened 2023-09-27 06:58 UTC by MelloTheCatLover

2023-09-27 16:30 UTC, galinabykova requested changes

2023-09-27 16:30 UTC, galinabykova commented on Task_1_1_2/.idea/gradle.xml
убери файлики из этой папки или докажи, что они нужны

2023-09-27 16:30 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/kozoliy/Polynomial.java
> +    public Polynomial(int[] coefficients) {
здесь входной параметр передаётся по значению или по ссылке?

2023-09-27 16:30 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/kozoliy/TestPolynomial.java
> +        Polynomial.main(new String[0]);
в этой задаче ты должен пройти порог по покрытию без этого теста

2023-09-27 16:30 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/kozoliy/TestPolynomial.java
> +        assertTrue(result.equals(expected));
нужно использовать AssertEquals, он красивую понятную строчку выводит, когда тест крашится

2023-09-27 16:30 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/kozoliy/TestPolynomial.java
хочется хотя бы пару тестов на каждую операция, проверь всякие краевые случаи и т.д.

2023-09-27 16:30 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/kozoliy/Polynomial.java
> +    public boolean equals(Polynomial other) {
здесь неверный класс входного параметра. Используй override для автоматической проверки компилятором, что метод переопределён

2023-09-28 12:07 UTC, MelloTheCatLover commented on Task_1_1_2/src/main/java/ru/nsu/kozoliy/Polynomial.java
> +    public Polynomial(int[] coefficients) {
По ссылке.

2023-09-29 06:07 UTC, galinabykova requested changes

2023-09-29 06:07 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/kozoliy/Polynomial.java
> +    public Polynomial(int[] coefficients) {
Что будет если изменить массив, переданный на вход коструктору, после создания объекта? Поменяется ли состояние полинома?

2023-10-02 08:55 UTC, galinabykova requested changes

2023-10-02 08:55 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/kozoliy/Polynomial.java
> +    public boolean equals(Object obj) {
вместе с equals надо переопределять hashCode

2023-10-02 08:55 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/kozoliy/Polynomial.java
> +    public boolean equals(Object obj) {
https://javarush.com/groups/posts/3957-kofe-breyk-168-zachem-pereopredeljatjh-metodih-equals-i-hashcode-v-java

2023-10-02 08:55 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/kozoliy/Polynomial.java
> +        this.coefficients = coefficients;
в этой строчке ты сохраняешь ссылку на массив, который пришёл тебе на вход. Твой полином и массив, переданный ему на вход, будут ссылаться на один и тот же объект, это плохо, потому что если кто-то поменяет массив извне, твой полином тоже внезапно поменяется

2023-10-02 13:18 UTC, galinabykova requested changes
reviewdog и hashcode

2023-10-04 03:34 UTC, galinabykova requested changes
reviewdog не забудь проверить

2023-10-04 03:34 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/kozoliy/TestMain.java
> +    void testMain () {
удали этот тест, main можно перенести в Polynomial. Порог по покрытию нужно пройти без этого теста

2023-10-04 09:24 UTC, galinabykova approved these changes

2023-10-12 05:47 UTC, merged