Task_1_2_1
MelloTheCatLover/OOP pull request #5
Opened 2023-10-08 11:54 UTC by MelloTheCatLover

2023-10-10 16:10 UTC, MelloTheCatLover commented
Надеюсь на мягкий дедлайн потянет

2023-10-10 18:49 UTC, galinabykova requested changes
Мягкий дедлайн засчитан. Исправь предупреждения reviewdog

2023-10-10 18:49 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/kozoliy/Main.class
удали этот файлик

2023-10-10 18:49 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        public String breadthFirstTraversal(StringBuilder bfsString) {
тебе нужно сделать итерирование, то есть реализовать функционал, с помощью которого пользователь сможет пробегаться по твоей коллекции. То есть твоя коллекция должна реализовывать интерфейс Iterable, и по ней можно будет пробегаться, например, с помощью for each

2023-10-10 18:49 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +         * @return `true`, если деревья равны, иначе `false`.
нужно в спецификации подробнее описать, что такое "деревья равны" в твоём случае

2023-10-16 17:08 UTC, MelloTheCatLover commented
Вообще я до конца не понял, понял ли я Iterable. Я написал рабочий код, но слабо понял про ConcurrentModificationExeption. В общем, можете посмотреть код, так нет тестов, нормального оформления, я его добавлю как только код будет правильно функционировать

2023-10-16 19:59 UTC, galinabykova requested changes
reviedog. Общая идея итератора верна, с CME мне непонятно, что ты реализуешь. Если тебе не очень понятно CME, сформулируй и задай вопросы, можно здесь, можно в телеграмм.

2023-10-16 19:59 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        private int countM;
нужно более осмысленное название, непонятно что это

2023-10-16 19:59 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        private int countM;
не могу найти кусок кода, в котором эта переменная инициализируется

2023-10-16 19:59 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        private int countM;
и меняется

2023-10-18 05:37 UTC, galinabykova requested changes
reviewdog

2023-10-18 05:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        private int countM;
.

2023-10-18 05:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +    public static class Tree<T> implements Iterable<T> {
почему ты решил сделать этот класс static?

2023-10-18 05:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +         * @return `true`, если деревья равны, иначе `false`.
.

2023-10-18 05:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        private class TreeIterator implements Iterator<T> {
а что это за итератор?

2023-10-18 05:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        private class TreeIterator implements Iterator<T> {
мы здесь просто пробегаемся по детям, да?

2023-10-18 05:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +         * Выполняет обход дерева в ширину и выводит значения узлов в порядке обхода.
кажется, это неверная спецификация

2023-10-18 05:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        public Iterator<T> iterator() {
на самом деле я бы сделала этот итератор в порядке Bfs или Dfs. Уж очень это нетипичное итерирования для дерева

2023-10-18 05:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/kozoliy/TreeInterpretation.java
> +        public Iterator<T> iterator() {
но можешь это не менять

2023-10-18 08:14 UTC, galinabykova requested changes
reviewdog

2023-10-18 10:23 UTC, galinabykova approved these changes

2023-10-18 10:33 UTC, MelloTheCatLover commented
Ура. Не нашел как смайлик кота оставить :)

2023-11-08 10:01 UTC, merged