Task_1_3_1
MelloTheCatLover/OOP pull request #9
Opened 2023-11-08 17:21 UTC by MelloTheCatLover

2023-11-08 17:42 UTC, galinabykova requested changes

2023-11-08 17:42 UTC, galinabykova commented on Task_1_2_2/build/classes/java/main/ru/nsu/kozoliy/AdjacencyListInterpretation.class
удали все ненужные файлики

2023-11-08 17:42 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/kozoliy/TestFindStrings.java
> +        ArrayList<Integer> result = generateFile(1000000, "hello", "file.txt");
файлик должен быть больше буффера и примерно 15 Гб

2023-11-08 17:42 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/kozoliy/FindString.java
> +        while (true) {
возможно, пропустила, объясни, пожалуйста, что происходит, если подстрока начинается на конце одной чанки и заканчивается в другой? обрабатывается ли у тебя этот случай?

2023-11-09 08:20 UTC, MelloTheCatLover commented on Task_1_3_1/src/main/java/ru/nsu/kozoliy/FindString.java
> +        while (true) {
![image](https://github.com/MelloTheCatLover/OOP/assets/125788433/706a4688-c3fe-4b1f-92a9-9714ddc1d6a8)
![изображение_2023-11-09_151650971](https://github.com/MelloTheCatLover/OOP/assets/125788433/8f967456-c014-482e-8273-c35387b8e2f3)


На тесте видно, что такие тесты проходят. Номер буквы в префиксном массиве(targetIndex) не обнуляется при прочитывании нового чанка. Проверка происходит в чанке(от 0 до длины текста чанка), общая проверка происходит от 0 до конца файла, номер чанка увеличивается после того как проверился очередной фрагмент.

Надеюсь смог объяснил. В сообщениях не так просто

2023-11-09 08:20 UTC, MelloTheCatLover commented on Task_1_3_1/src/test/java/ru/nsu/kozoliy/TestFindStrings.java
> +        ArrayList<Integer> result = generateFile(1000000, "hello", "file.txt");
Увеличил

2023-11-09 08:22 UTC, MelloTheCatLover commented on Task_1_2_2/build/classes/java/main/ru/nsu/kozoliy/AdjacencyListInterpretation.class
Что-то еще нужно удалить?

2023-11-09 09:35 UTC, galinabykova commented on Task_1_2_2/build/classes/java/main/ru/nsu/kozoliy/AdjacencyListInterpretation.class
ещё build в Task_2_2_2. Вообще желательно делать ветку от mainа и добавлять только папку с текущем заданием

2023-11-09 09:44 UTC, galinabykova requested changes
reviewdog

2023-11-09 09:44 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/kozoliy/TestFindStrings.java
> +        ArrayList<Integer> result = generateFile(1500000000, "hello", "file.txt");
а это точно 15 Гб? Кажется, что тут 1.5. Такие большие числа, кстати, можно писать с нижними подчёркиваниями (вот так: 10_000_000) для повышения читаемости

2023-11-09 09:44 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/kozoliy/FindString.java
> +    private void openFile(String filename, FileType FileType) throws IOException {
а открытый здесь файл где-то закрывается?

2023-11-09 17:58 UTC, MelloTheCatLover commented on Task_1_3_1/src/main/java/ru/nsu/kozoliy/FindString.java
> +    private void openFile(String filename, FileType FileType) throws IOException {
Теперь да)

2023-11-09 17:58 UTC, MelloTheCatLover commented on Task_1_3_1/src/test/java/ru/nsu/kozoliy/TestFindStrings.java
> +        ArrayList<Integer> result = generateFile(1500000000, "hello", "file.txt");
Увеличил еще раз. Не знал, что так можно писать, спасибо!

2023-11-10 08:02 UTC, galinabykova requested changes
удали ненужные файлики, такие, как build в Task_1_2_2 и исправь замечания reviewdog

2023-11-12 06:22 UTC, galinabykova requested changes
reviewdog

2023-11-12 12:01 UTC, galinabykova approved these changes

2023-11-13 07:11 UTC, merged